### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by MisterM23** [techfreaque/octo-ui-2#1]
Hi, 
when i try to install octo-ui-2 I get this error in the logs:

octobot_tentacles_manager.api.util.tentacles_management
Exception during InstallWorker processing: (error: NotImplementedError)

My Octobot installation runs on a vps in docker-compose with nginx proxy manager 

Any ideas?

**Comment by techfreaque** [comment]
Hi there,

thanks a lot for reporting the issue. I just pushed a new version which should work with the latest octobot version.
I'm mainly focusing on [octane](https://github.com/techfreaque/octane) my own octobot distribution, so there are still things that dont work on octobot, as i needed to change to core of octbot quite a bit.

**Comment by MisterM23** [comment]
Hi techfreaque,

Thanks for the quick reply. Unfortunately i get the same error. See detailed log below.

2024-06-22 11:20:34 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:239      
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/octobot_tentacles_manager/api/util/tentacles_management.py", line 28, in manage_tentacles
    session = authenticator.get_aiohttp_session() if authenticator and authenticator.is_logged_in() \
  File "/opt/venv/lib/python3.10/site-packages/octobot_commons/authentication.py", line 84, in get_aiohttp_session
    raise NotImplementedError

My Octobot runs on an VPS with the nginx-proxy-manager. I use Portainer to install the stack. Also Letsencrypt is used.

I want to give octane a try. Seem to be a great piece of work. Do you provide a docker-compose file for octane?

Many Thanks 
MisterM23

**Comment by techfreaque** [comment]
Ahh I see, I'm already at octobot 1.0.11 which isnt released yet. It should be released in a couple of days, then it should work (at least it works for me in the local and docker version).

unfortuantely there is no docker-compose file. I'm using a bash script (linux-docker_install_or_update.sh) build the Dockerfile in /scripts and run it.
Does that work for you?
Here you can find the steps to install it: https://github.com/techfreaque/octane/blob/main/readme/installation-end-user.md#docker-on-linux-installation

**Comment by MisterM23** [comment]
Thanks a lot. I wait for the 1.0.11 version and try it again. Meanwhile, I will test octane on a local VM.
